### ISSUE TITLE
'stromnetzgraz:energy_consumption:...' not present for second meter

### ISSUE THREAD

**Issue by danilichti** [dreautall/ha-stromnetzgraz#15]
After installing and configuring the Stromnetz device, I only see one 'stromnetzgraz:energy_consumption:..' sensor/entity and am unable to add the second meter to the energy dashboard.

![CleanShot 2024-03-02 at 08 10 03](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/66cd2673-ea79-45f0-96e8-1698f47e4927)

![CleanShot 2024-03-02 at 08 10 39](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/02132354-9efa-4e98-8732-8ed995160ca8)

**Comment by dreautall** [comment]
Hi, do both meters have actual consumption values in the official web portal? "Empty" entities will not be added.

**Comment by danilichti** [comment]
Hi, 
yes both methers have actual values and IME enabled.

Here is the web portal data for the meter that can be added:

![CleanShot 2024-03-02 at 08 27 39](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/baccb884-cdce-4a8b-9a02-7be522cec8aa)


Here the data for the meter that CAN'T be added:

![CleanShot 2024-03-02 at 08 27 47](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/abc52301-520d-453f-acb2-edd803bc3792)

**Comment by dreautall** [comment]
Okay.. stuff like this is notoriously hard to debug :(

In the Integrations tab, click on Stromnetz Graz - can you please enable debug logging for the integration (lowest button on the left), reload the integration (behind the dot menu on the right next to the Stromnetz Mail Address), wait a bit, then disable logging again - it will automatically download a log file. Could you please provide that? It is a clear text file, so check through it and delete any sensitive stuff please.

Alternatively, if you know a bit of Python, you could check if the stromnetzgraz script properly returns data for both meters, a short snippet is available in the README: https://github.com/dreautall/stromnetzgraz

**Comment by danilichti** [comment]
[home-assistant_stromnetzgraz_2024-03-02T07-42-18.512Z.log](https://github.com/dreautall/ha-stromnetzgraz/files/14468452/home-assistant_stromnetzgraz_2024-03-02T07-42-18.512Z.log)

**Comment by danilichti** [comment]
Sorry, no Python knowledge here. 
It seems, when starting up, the XXXX60 meter doesn't show any information. After the second fetch (6h), it shows data. 

![CleanShot 2024-03-02 at 08 52 04](https://github.com/dreautall/ha-stromnetzgraz/assets/73495201/429476a2-a237-4e8b-a700-683ec40ae85d)

**Comment by danilichti** [comment]
Just installed the 0.13 update and re-added the integration. This log file might be more relevant.

**Comment by dreautall** [comment]
Hi, you uploaded the same log two times, seems to be the old version (not that the version changed anything despite fixing the deprecated warning).

Could you maybe let the debug log run until the second fetch (~6 hours) occurs and both sensors at least show up in HA?

Thank you!

**Comment by danilichti** [comment]
[home-assistant_stromnetzgraz_2024-03-02T15-53-40.864Z.log](https://github.com/dreautall/ha-stromnetzgraz/files/14470374/home-assistant_stromnetzgraz_2024-03-02T15-53-40.864Z.log)

Sorry, here is the log file I intended to upload. I'll have the debug log run until tomorrow.

**Comment by dreautall** [comment]
That log is strange, it only shows errors for the integration, not even one sensor was set up successfuly. looks like wrong login credentials. Was this from a successful attempt to add the integration?

**Comment by danilichti** [comment]
That might have been the case. I thought that it could help as well.
 Here is the log file which ran since yesterday:

[home-assistant_stromnetzgraz_2024-03-03T08-47-11.232Z.log](https://github.com/dreautall/ha-stromnetzgraz/files/14472258/home-assistant_stromnetzgraz_2024-03-03T08-47-11.232Z.log)

No entries for the other meter at all.

**Comment by danilichti** [comment]
Hi @dreautall,

would there be anything to do from my side to make this work? 
Perhaps contacting Stromnetz Graz about the issues?

**Comment by dreautall** [comment]
Sorry for my absence - I was unavailable the last two weeks.

It is really hard to debug something like this, and there seems to be no one else with the issue :( It looks like for some reason the second meter is not fetched properly via the underlying `stromnetzgraz` python component. As the website shows the second meter and also only uses the API I guess it's a "me issue", not from Stromnetz Graz. It could be something very simple after all, but as there is no official API documentation I can't fix the issue without being able to reproduce it in my own account... which I can't.

The only thing that I can offer is that you send me the traffic log of the official website, so that I can check the responses. Login to the website, open the dev console (chrome: ctrl+shift+i), go to the network tab of the console, make sure "preserve log" is enabled, then get the 15min interval data for one meter for the last 7 days, switch meter, do the same, right-click any entry in the network tab and do "save all as HAR without context".

The .har file will again be a text file. Please delete anything private. What you should probably search for: your address, name, meter ID, installation ID, an authentication token (in every call, ctrl+f for the word "Bearer" - the long string afterwards). You could also email it to me (github[at sign]vogt.pw), I'll promise to delete it afterwards and not caring about who you are 😄

**Comment by phaze75** [comment]
Hi @dreautall, hi @danilichti,

Were you able to solve the issue? I am having the same issue with v0.1.14. The data of my nighttime tariff smart meter is processed properly. The data of my daytime tariff smart meter is not processed at all. Both devices have been created correctly though. The numbers match with my account.

Best regards!

**Comment by dreautall** [comment]
Hi, yes we solved this with the .har file. If you want we can try the same, see my comment above how to do it and where to send it to!
