### ISSUE TITLE
No entity shows up

### ISSUE THREAD

**Issue by petwri** [dreautall/ha-stromnetzgraz#17]
So I have installed the integration as described in the Readme. Adding my serviceportal-credentials didn't produce any errors, but the only entity showing is `update.stromnetz_graz_integration_update`.

What did i do wrong? I am on v0.1.14.

**Comment by dreautall** [comment]
Hi, on the integrations screen when you click on Stromnetz Graz, does it show any devices or entities there? Each meter should be a device and provide two sensors (you see on that screen).

The sensor to use on the Energy dashboard (the `stromnetzgraz:energy_consumption:1234` with colons instead of dots) might take up to twelve hours to show up (as it's fetching historic data first).

**Comment by petwri** [comment]
Under Integration entries, it shows an entry, but it says "No devices or
entities".

**Comment by dreautall** [comment]
When you log in the web portal with your credentials, do you see your meters there? Did you configure them for daily or 15 min interval?

**Comment by petwri** [comment]
Thanks for the hint.

The webportal is indeed empty. I'll check with Stromnetz Graz.

**Comment by dreautall** [comment]
If you have any further issues after the web portal shows data let me know!

You need to re-add the integration the day or two after the first data shows up, the integration only checks for sensors on first start-up.
